Repository openclimatefix/nowcasting_dataset, pull requests merged in 2021-09, with the labels that each got.

#120 adding .flake8 file to set line length to 100 chars
  .flake8
Labels: size-small

#152 Get `nowcasting_dataset` running on OCF's on-premises server
  conftest.py
  environment.yml
  nowcasting_dataset/cloud/gcp.py
  nowcasting_dataset/cloud/local.py
  nowcasting_dataset/cloud/utils.py
  nowcasting_dataset/config/README.md
  nowcasting_dataset/config/example.yaml
  nowcasting_dataset/config/gcp.yaml
  nowcasting_dataset/config/load.py
  nowcasting_dataset/config/model.py
  nowcasting_dataset/config/on_premises.yaml
  nowcasting_dataset/config/save.py
  nowcasting_dataset/data_sources/pv_data_source.py
  nowcasting_dataset/dataset/batch.py
  nowcasting_dataset/dataset/split/split.py
  nowcasting_dataset/utils.py
  requirements.txt
  scripts/copy_from_gcp_to_aws.py
  scripts/get_raw_pv_gsp_data.py
  scripts/prepare_ml_data.py
  tests/config/nwp_size_test.yaml
  tests/config/test.yaml
  tests/config/test_config.py
  tests/dataset/test_split.py
  tests/test_datamodule.py
Labels: enhancement, data, infrastructure/on-premises hardware

#173 Updating README.md, environment.yml and requirements.txt
  README.md
  environment.yml
  requirements.txt
Labels: enhancement

#125 Add docstring linters
  .github/workflows/linters.yaml
  .github/workflows/python-app.yml
  nowcasting_dataset/__init__.py
  nowcasting_dataset/cloud/__init__.py
  nowcasting_dataset/cloud/aws.py
  nowcasting_dataset/cloud/gcp.py
  nowcasting_dataset/cloud/local.py
  nowcasting_dataset/cloud/utils.py
  nowcasting_dataset/config/__init__.py
  nowcasting_dataset/config/load.py
  nowcasting_dataset/config/model.py
  nowcasting_dataset/config/save.py
  nowcasting_dataset/consts.py
  nowcasting_dataset/data_sources/__init__.py
  nowcasting_dataset/data_sources/data_source.py
  nowcasting_dataset/data_sources/datetime_data_source.py
  nowcasting_dataset/data_sources/gsp/__init__.py
  nowcasting_dataset/data_sources/gsp/eso.py
  nowcasting_dataset/data_sources/gsp/gsp_data_source.py
  nowcasting_dataset/data_sources/gsp/pvlive.py
  nowcasting_dataset/data_sources/nwp_data_source.py
  nowcasting_dataset/data_sources/pv_data_source.py
  nowcasting_dataset/data_sources/satellite_data_source.py
  nowcasting_dataset/data_sources/topographic_data_source.py
  nowcasting_dataset/dataset/__init__.py
  nowcasting_dataset/dataset/batch.py
  nowcasting_dataset/dataset/datamodule.py
  nowcasting_dataset/dataset/datasets.py
  nowcasting_dataset/dataset/example.py
  nowcasting_dataset/dataset/split/method.py
  nowcasting_dataset/dataset/split/model.py
  nowcasting_dataset/dataset/split/split.py
  nowcasting_dataset/dataset/validate.py
  nowcasting_dataset/geospatial.py
  nowcasting_dataset/square.py
  nowcasting_dataset/time.py
  nowcasting_dataset/utils.py
  setup.py
Labels: good first issue
