Repository openclimatefix/nowcasting_dataset, pull requests merged in 2021-11, with the labels that each got.

#307 Big new design Part 2 :)
  README.md
  conftest.py
  environment.yml
  notebooks/2021-09/2021-09-07/sat_data.py
  nowcasting_dataset/config/__init__.py
  nowcasting_dataset/config/model.py
  nowcasting_dataset/config/on_premises.yaml
  nowcasting_dataset/consts.py
  nowcasting_dataset/data_sources/__init__.py
  nowcasting_dataset/data_sources/data_source.py
  nowcasting_dataset/data_sources/data_source_list.py
  nowcasting_dataset/data_sources/datasource_output.py
  nowcasting_dataset/data_sources/datetime/datetime_data_source.py
  nowcasting_dataset/data_sources/datetime/datetime_model.py
  nowcasting_dataset/data_sources/fake.py
  nowcasting_dataset/data_sources/gsp/eso.py
  nowcasting_dataset/data_sources/gsp/gsp_data_source.py
  nowcasting_dataset/data_sources/gsp/gsp_model.py
  nowcasting_dataset/data_sources/gsp/pvlive.py
  nowcasting_dataset/data_sources/metadata/metadata_data_source.py
  nowcasting_dataset/data_sources/nwp/nwp_data_source.py
  nowcasting_dataset/data_sources/nwp/nwp_model.py
  nowcasting_dataset/data_sources/pv/pv_data_source.py
  nowcasting_dataset/data_sources/satellite/satellite_data_source.py
  nowcasting_dataset/data_sources/sun/raw_data_load_save.py
  nowcasting_dataset/data_sources/sun/sun_data_source.py
  nowcasting_dataset/data_sources/topographic/topographic_data_source.py
  nowcasting_dataset/dataset/README.md
  nowcasting_dataset/dataset/batch.py
  nowcasting_dataset/dataset/datamodule.py
  nowcasting_dataset/dataset/datasets.py
  nowcasting_dataset/dataset/split/method.py
  nowcasting_dataset/dataset/split/split.py
  nowcasting_dataset/dataset/xr_utils.py
  nowcasting_dataset/filesystem/utils.py
  nowcasting_dataset/geospatial.py
  nowcasting_dataset/manager.py
  nowcasting_dataset/time.py
  nowcasting_dataset/utils.py
  scripts/generate_data_for_tests/get_test_data.py
  scripts/prepare_ml_data.py
  setup.py
  tests/config/test_config.py
  tests/data_sources/gsp/test_gsp_model.py
  tests/data_sources/satellite/test_satellite_data_source.py
  tests/data_sources/satellite/test_satellite_model.py
  tests/data_sources/sun/test_sun_model.py
  tests/data_sources/test_data_source_list.py
  tests/data_sources/test_nwp_data_source.py
  tests/data_sources/test_pv_data_source.py
  tests/dataset/test_batch.py
  tests/filesystem/test_local.py
  tests/test_datamodule.py
  tests/test_dataset.py
  tests/test_manager.py
  tests/test_utils.py
Labels: enhancement, refactoring

#330 Remove optional torch dependencies from setup
  setup.py
Labels: enhancement

#332 Remove Datetime Data Source
  nowcasting_dataset/data_sources/__init__.py
  nowcasting_dataset/data_sources/datetime/__init__.py
  nowcasting_dataset/data_sources/datetime/datetime_data_source.py
  nowcasting_dataset/data_sources/datetime/datetime_model.py
  nowcasting_dataset/data_sources/fake.py
  nowcasting_dataset/dataset/batch.py
  nowcasting_dataset/time.py
  nowcasting_dataset/utils.py
  tests/data_sources/test_datasource_output.py
  tests/data_sources/test_datetime.py
  tests/test_time.py
  tests/test_utils.py
Labels: enhancement, refactoring

#350 removed underscore in DataSource
  nowcasting_dataset/data_sources/data_source.py
  nowcasting_dataset/data_sources/nwp/nwp_data_source.py
  nowcasting_dataset/data_sources/satellite/satellite_data_source.py
Labels: enhancement, refactoring

#357 Convert NWP grib files to Zarr intermediate
  README.md
  notebooks/plot_NWP_zarr.ipynb
  scripts/convert_NWP_grib_to_zarr.py
  scripts/download_UK_Met_Office_NWPs_from_CEDA.sh
Labels: enhancement, data

#394 moving NWP scripts to nwp repo
  README.md
  scripts/convert_NWP_grib_to_zarr.py
  scripts/download_UK_Met_Office_NWPs_from_CEDA.sh
Labels: enhancement, refactoring

#375 Speed up gsp locations
  nowcasting_dataset/data_sources/gsp/gsp_data_source.py
Labels: enhancement

#397 try CI - PVlive errors
  nowcasting_dataset/data_sources/gsp/eso.py
  tests/data_sources/gsp/test_gsp_pvlive.py
Labels: bug

#396 Bug/manger sun
  nowcasting_dataset/config/gcp.yaml
  nowcasting_dataset/config/on_premises.yaml
  nowcasting_dataset/data_sources/data_source.py
  nowcasting_dataset/data_sources/sun/sun_data_source.py
  tests/test_manager.py
Labels: bug

#365 add methods to get centers from list of coords
  nowcasting_dataset/geospatial.py
  tests/test_geospatial.py
Labels: enhancement

#387 Update NWPDataSource for new NWP Zarr
  README.md
  notebooks/plot_NWP_zarr.ipynb
  nowcasting_dataset/config/on_premises.yaml
  nowcasting_dataset/consts.py
  nowcasting_dataset/data_sources/nwp/nwp_data_source.py
  pytest.ini
  scripts/prepare_ml_data.py
  tests/data_sources/test_nwp_data_source.py
Labels: data

#404 Configure loggers
  nowcasting_dataset/consts.py
  nowcasting_dataset/manager.py
  nowcasting_dataset/utils.py
  scripts/prepare_ml_data.py
  tests/test_manager.py
Labels: enhancement

#412 Fix "RuntimeError: Example is wrong shape"
  nowcasting_dataset/data_sources/nwp/nwp_data_source.py
Labels: bug

#431 Enable `check_path_exists` to work with wildcards.
  nowcasting_dataset/filesystem/utils.py
  tests/filesystem/test_local.py
Labels: bug

#436 Bug/435 open sat data
  nowcasting_dataset/data_sources/satellite/satellite_data_source.py
Labels: bug

#445 Set n_validation_batches to 0
  nowcasting_dataset/config/model.py
  nowcasting_dataset/config/on_premises.yaml
  nowcasting_dataset/manager.py
Labels: bug

#453 Use `multiprocessing.Pool` instead of `ProcessPoolExecutor`
  nowcasting_dataset/manager.py
Labels: enhancement, refactoring

#459 10x speedup loading Zarrs by using chunks=auto!
  nowcasting_dataset/data_sources/nwp/nwp_data_source.py
  nowcasting_dataset/data_sources/satellite/satellite_data_source.py
Labels: enhancement

#461 Bug/460 gsp time
  nowcasting_dataset/data_sources/gsp/gsp_data_source.py
  nowcasting_dataset/data_sources/pv/pv_data_source.py
  tests/data_sources/gsp/test_gsp_data_source.py
Labels: bug

#472 Manager._get_first_batches_to_create() should set first batch to 0 if no batches are on disk
  nowcasting_dataset/filesystem/utils.py
Labels: bug

#364 make pv coords more relastic
  nowcasting_dataset/data_sources/fake.py
  nowcasting_dataset/data_sources/satellite/satellite_data_source.py
Labels: enhancement

#492 NWP fixes
  notebooks/plot_NWP_zarr.ipynb
  nowcasting_dataset/config/on_premises.yaml
  nowcasting_dataset/data_sources/nwp/nwp_data_source.py
  nowcasting_dataset/manager.py
Labels: bug, data

#497 drop_gsp_north_of_boundary
  nowcasting_dataset/config/on_premises.yaml
  nowcasting_dataset/data_sources/gsp/gsp_data_source.py
  nowcasting_dataset/data_sources/pv/pv_data_source.py
  tests/data_sources/gsp/test_gsp_data_source.py
Labels: enhancement

#506 compute normalisation stats from training set
  notebooks/compute_stats_from_batches.ipynb
Labels: enhancement

#510 Add only loading some of the netcdf files
  nowcasting_dataset/dataset/batch.py
  tests/dataset/test_batch.py
Labels: enhancement
